#!/usr/bin/env python3
"""Generate the translation status table in README.md from the resource files.

Reads every ``app/src/main/res/values-<locale>/*.xml`` directory, computes
how much of the default (English) string set each locale defines, and
rewrites the block between ``<!-- translation-status:start -->`` and
``<!-- translation-status:end -->`` in ``README.md``. Nothing outside the
markers is touched. The table is GENERATED - never edit it by hand; a
status table that lies is worse than none, so
``TranslationStatusTest`` (app/src/test) fails when the block is stale.

Counting rule (mirrored exactly by the Kotlin test):

* Denominator = translatable items in ``values/``: every ``<string>``,
  ``<plurals>`` and ``<string-array>`` whose ``translatable`` attribute is
  not ``"false"``. A ``<plurals>`` counts as ONE item regardless of how
  many quantities it declares, because a locale either provides it or does
  not.
* Numerator = how many of those names the locale defines (in any file of
  its directory). Names the locale defines that do not exist in the default
  locale are ignored here - Android Lint's ``ExtraTranslation`` check
  rejects them at build time.
* Percentage is truncated to a whole number, so ``100%`` means complete.

Coverage measures PRESENCE, not quality: a translated string that happens
to be identical to the English text is indistinguishable from an
untranslated one, and nothing here checks that a translation is good.

Which directories count as a locale: only a directory whose qualifier is a
locale and nothing else - ``values-ru``, ``values-pt-rBR`` (region) or the
BCP 47 form ``values-b+sr+Latn``. Every other configuration qualifier that
Android allows on a ``values-`` directory - ``values-night``, ``values-v31``,
``values-land``, ``values-sw600dp``, ``values-ldrtl`` and so on - is not a
language and is excluded, as is a locale combined with another qualifier
(``values-ru-night`` would only apply in dark theme and is not a
translation). See ``is_locale_qualifier``.

With zero translations the block states that plainly, together with the
number of translatable items, rather than rendering an empty table.

Usage::

    python3 scripts/translation_status.py            # rewrite README.md
    python3 scripts/translation_status.py --check    # exit 1 if stale
    python3 scripts/translation_status.py --print    # table to stdout only
"""

import argparse
import os
import re
import sys
import xml.etree.ElementTree as ET

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)
DEFAULT_RES = os.path.join(REPO, "app", "src", "main", "res")
DEFAULT_README = os.path.join(REPO, "README.md")

START_MARKER = "<!-- translation-status:start -->"
END_MARKER = "<!-- translation-status:end -->"
GENERATED_NOTE = (
    "<!-- Generated by scripts/translation_status.py - do not edit by hand. -->"
)

TRANSLATABLE_TAGS = ("string", "plurals", "string-array")

# ``values-xx`` or ``values-xx-rYY`` (ISO 639-1 language, optional ISO 3166
# region), or ``values-b+<language>[+<subtag>...]`` (BCP 47). Anchored on
# both ends so a trailing qualifier (``ru-night``) does not match.
_LEGACY_LOCALE = re.compile(r"^[a-z]{2}(-r[A-Z]{2})?$")
_BCP47_LOCALE = re.compile(r"^b\+[a-zA-Z]{2,3}(\+[a-zA-Z0-9]{1,8})*$")

# English display names for the codes most likely to appear. The name is
# informational; unknown codes fall back to the code itself and the table
# stays correct. Keys use the directory qualifier spelling.
LANGUAGE_NAMES = {
    "ar": "Arabic",
    "bn": "Bengali",
    "cs": "Czech",
    "da": "Danish",
    "de": "German",
    "el": "Greek",
    "es": "Spanish",
    "fa": "Persian",
    "fi": "Finnish",
    "fr": "French",
    "gu": "Gujarati",
    "he": "Hebrew",
    "hi": "Hindi",
    "hu": "Hungarian",
    "id": "Indonesian",
    "in": "Indonesian",
    "it": "Italian",
    "iw": "Hebrew",
    "ja": "Japanese",
    "kn": "Kannada",
    "ko": "Korean",
    "ml": "Malayalam",
    "mr": "Marathi",
    "nb": "Norwegian Bokmål",
    "nl": "Dutch",
    "pl": "Polish",
    "pt": "Portuguese",
    "pt-rBR": "Portuguese (Brazil)",
    "pt-rPT": "Portuguese (Portugal)",
    "ro": "Romanian",
    "ru": "Russian",
    "sk": "Slovak",
    "sv": "Swedish",
    "ta": "Tamil",
    "te": "Telugu",
    "th": "Thai",
    "tr": "Turkish",
    "uk": "Ukrainian",
    "vi": "Vietnamese",
    "zh-rCN": "Chinese (Simplified)",
    "zh-rTW": "Chinese (Traditional)",
    "b+sr+Latn": "Serbian (Latin)",
    "b+zh+Hans": "Chinese (Simplified)",
    "b+zh+Hant": "Chinese (Traditional)",
}


def is_locale_qualifier(qualifier):
    """True when a ``values-<qualifier>`` directory is a language, and only that."""
    return bool(_LEGACY_LOCALE.match(qualifier) or _BCP47_LOCALE.match(qualifier))


def locale_dirs(res_dir):
    """Sorted ``(qualifier, path)`` for every locale directory under ``res``."""
    out = []
    for name in sorted(os.listdir(res_dir)):
        if not name.startswith("values-"):
            continue
        qualifier = name[len("values-"):]
        if is_locale_qualifier(qualifier) and os.path.isdir(os.path.join(res_dir, name)):
            out.append((qualifier, os.path.join(res_dir, name)))
    return out


def translatable_names(values_dir, respect_translatable_flag=True):
    """Names of the string items declared in every ``.xml`` file of a directory."""
    names = set()
    for fname in sorted(os.listdir(values_dir)):
        if not fname.endswith(".xml"):
            continue
        root = ET.parse(os.path.join(values_dir, fname)).getroot()
        if root.tag != "resources":
            continue
        for el in root:
            if el.tag not in TRANSLATABLE_TAGS:
                continue
            if respect_translatable_flag and el.get("translatable") == "false":
                continue
            name = el.get("name")
            if name:
                names.add(name)
    return names


def compute_status(res_dir=DEFAULT_RES):
    """Return ``(total, [(qualifier, translated_count), ...])``."""
    default_names = translatable_names(os.path.join(res_dir, "values"))
    rows = []
    for qualifier, path in locale_dirs(res_dir):
        # A locale's own translatable="false" entries are irrelevant: what
        # matters is which default-locale names it provides.
        defined = translatable_names(path, respect_translatable_flag=False)
        rows.append((qualifier, len(defined & default_names)))
    return len(default_names), rows


def percent(count, total):
    return 0 if total == 0 else count * 100 // total


def language_name(qualifier):
    return LANGUAGE_NAMES.get(qualifier, qualifier)


def render(total, rows):
    """The Markdown that goes between the markers (without the markers)."""
    lines = [GENERATED_NOTE]
    if not rows:
        lines.append(
            "No translations yet - the app ships in English only, with "
            "%d translatable strings (each plural counted once). "
            "See [docs/translating.md](docs/translating.md) to add one." % total
        )
        return "\n".join(lines)
    lines.append("| Language | Code | Translated | Coverage |")
    lines.append("| --- | --- | ---: | ---: |")
    for qualifier, count in rows:
        lines.append(
            "| %s | `%s` | %d / %d | %d%% |"
            % (language_name(qualifier), qualifier, count, total, percent(count, total))
        )
    lines.append("")
    lines.append(
        "Coverage counts strings the translation defines, out of %d translatable "
        "items in English (each plural counted once); it measures presence, not "
        "quality. Regenerate with `python3 scripts/translation_status.py`." % total
    )
    return "\n".join(lines)


def splice(readme_text, block):
    """Replace the marked block in README text; raise if markers are missing."""
    start = readme_text.find(START_MARKER)
    end = readme_text.find(END_MARKER)
    if start < 0 or end < 0 or end < start:
        raise SystemExit(
            "README.md is missing the %s / %s markers" % (START_MARKER, END_MARKER)
        )
    return (
        readme_text[: start + len(START_MARKER)]
        + "\n"
        + block
        + "\n"
        + readme_text[end:]
    )


def main(argv=None):
    ap = argparse.ArgumentParser(
        description=__doc__.split("\n\n")[0],
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    ap.add_argument("--res", default=DEFAULT_RES, help="path to app/src/main/res")
    ap.add_argument("--readme", default=DEFAULT_README, help="path to README.md")
    mode = ap.add_mutually_exclusive_group()
    mode.add_argument("--check", action="store_true",
                      help="exit 1 if the README block is stale; change nothing")
    mode.add_argument("--print", action="store_true",
                      help="print the generated block to stdout; change nothing")
    args = ap.parse_args(argv)

    total, rows = compute_status(args.res)
    block = render(total, rows)

    if args.print:
        print(block)
        return 0

    with open(args.readme, encoding="utf-8") as fh:
        current = fh.read()
    updated = splice(current, block)

    if args.check:
        if updated != current:
            sys.stderr.write(
                "README.md translation status is stale - run "
                "python3 scripts/translation_status.py\n"
            )
            return 1
        print("README.md translation status is up to date.")
        return 0

    if updated == current:
        print("README.md translation status already up to date.")
    else:
        with open(args.readme, "w", encoding="utf-8") as fh:
            fh.write(updated)
        print("README.md translation status updated (%d locale(s), %d items)."
              % (len(rows), total))
    return 0


if __name__ == "__main__":
    sys.exit(main())
